// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: channel.proto

package godesk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelRequest DataStream 双向数据流的基础消息
// key 字段定义了消息类型，data 字段包含具体的数据（JSON 格式）
type ChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端唯一标识
	ClientUuid string `protobuf:"bytes,1,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	// 数据类型（key 定义见下方注释）
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 数据（JSON 格式，具体结构见各 key 的说明）
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelRequest) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

func (x *ChannelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChannelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// RegisterData 设备注册数据（key = "register"）
// 方向：被控端 -> 服务器
type RegisterData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备 UUID
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// 操作系统：windows, darwin, linux
	Os string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	// 设备名称
	DeviceName    string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterData) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterData) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// HeartbeatData 心跳数据（key = "heartbeat"）
// 方向：被控端 -> 服务器
type HeartbeatData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 可选：当前会话ID（如果有）
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatData) Reset() {
	*x = HeartbeatData{}
	mi := &file_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatData) ProtoMessage() {}

func (x *HeartbeatData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatData.ProtoReflect.Descriptor instead.
func (*HeartbeatData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ControlStartedData 控制开始通知数据（key = "control_started"）
// 方向：服务器 -> 被控端
type ControlStartedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 控制端 UUID
	ControllerUuid string `protobuf:"bytes,2,opt,name=controller_uuid,json=controllerUuid,proto3" json:"controller_uuid,omitempty"`
	// 控制端名称
	ControllerName string `protobuf:"bytes,3,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	// 是否请求完全控制权限
	RequestControl bool `protobuf:"varint,4,opt,name=request_control,json=requestControl,proto3" json:"request_control,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStartedData) Reset() {
	*x = ControlStartedData{}
	mi := &file_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStartedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStartedData) ProtoMessage() {}

func (x *ControlStartedData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStartedData.ProtoReflect.Descriptor instead.
func (*ControlStartedData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ControlStartedData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlStartedData) GetControllerUuid() string {
	if x != nil {
		return x.ControllerUuid
	}
	return ""
}

func (x *ControlStartedData) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

func (x *ControlStartedData) GetRequestControl() bool {
	if x != nil {
		return x.RequestControl
	}
	return false
}

func (x *ControlStartedData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ControlEndedData 控制结束通知数据（key = "control_ended"）
// 方向：服务器 -> 被控端
type ControlEndedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 断开原因: 0=主动断开, 1=连接超时, 2=网络错误, 3=被踢出, 4=程序退出
	Reason int32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 原因描述
	ReasonDesc string `protobuf:"bytes,3,opt,name=reason_desc,json=reasonDesc,proto3" json:"reason_desc,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEndedData) Reset() {
	*x = ControlEndedData{}
	mi := &file_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEndedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEndedData) ProtoMessage() {}

func (x *ControlEndedData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEndedData.ProtoReflect.Descriptor instead.
func (*ControlEndedData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{4}
}

func (x *ControlEndedData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlEndedData) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *ControlEndedData) GetReasonDesc() string {
	if x != nil {
		return x.ReasonDesc
	}
	return ""
}

func (x *ControlEndedData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ScreenStreamStatusData 屏幕流状态数据（key = "screen_stream_status"）
// 方向：被控端 -> 服务器 -> 控制端
type ScreenStreamStatusData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 状态: started, stopped, paused, error
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 状态描述/错误信息
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStreamStatusData) Reset() {
	*x = ScreenStreamStatusData{}
	mi := &file_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStreamStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStreamStatusData) ProtoMessage() {}

func (x *ScreenStreamStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStreamStatusData.ProtoReflect.Descriptor instead.
func (*ScreenStreamStatusData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenStreamStatusData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenStreamStatusData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScreenStreamStatusData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScreenStreamStatusData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StatusReportData 状态报告数据（key = "status_report"）
// 方向：被控端 -> 服务器
type StatusReportData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID（可选）
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 状态: online, busy, error
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 状态信息
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReportData) Reset() {
	*x = StatusReportData{}
	mi := &file_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReportData) ProtoMessage() {}

func (x *StatusReportData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReportData.ProtoReflect.Descriptor instead.
func (*StatusReportData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{6}
}

func (x *StatusReportData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StatusReportData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusReportData) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *StatusReportData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ControlRequest 发起控制请求（控制端 -> 服务器）
type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 控制端设备UUID
	ControllerUuid string `protobuf:"bytes,2,opt,name=controller_uuid,json=controllerUuid,proto3" json:"controller_uuid,omitempty"`
	// 控制端设备码
	ControllerCode uint64 `protobuf:"varint,3,opt,name=controller_code,json=controllerCode,proto3" json:"controller_code,omitempty"`
	// 控制端设备名称
	ControllerName string `protobuf:"bytes,4,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	// 被控端设备码
	TargetDeviceCode uint64 `protobuf:"varint,5,opt,name=target_device_code,json=targetDeviceCode,proto3" json:"target_device_code,omitempty"`
	// 被控端密码
	TargetPassword string `protobuf:"bytes,6,opt,name=target_password,json=targetPassword,proto3" json:"target_password,omitempty"`
	// 请求时间戳
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 是否请求完全控制权限（true=控制，false=仅查看）
	RequestControl bool `protobuf:"varint,8,opt,name=request_control,json=requestControl,proto3" json:"request_control,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{7}
}

func (x *ControlRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlRequest) GetControllerUuid() string {
	if x != nil {
		return x.ControllerUuid
	}
	return ""
}

func (x *ControlRequest) GetControllerCode() uint64 {
	if x != nil {
		return x.ControllerCode
	}
	return 0
}

func (x *ControlRequest) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

func (x *ControlRequest) GetTargetDeviceCode() uint64 {
	if x != nil {
		return x.TargetDeviceCode
	}
	return 0
}

func (x *ControlRequest) GetTargetPassword() string {
	if x != nil {
		return x.TargetPassword
	}
	return ""
}

func (x *ControlRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlRequest) GetRequestControl() bool {
	if x != nil {
		return x.RequestControl
	}
	return false
}

// ControlResponse 控制请求响应
type ControlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 是否接受请求
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 响应码: 0=接受, 1=拒绝, 2=设备忙, 3=密码错误, 4=设备不存在, 5=设备离线
	ResponseCode int32 `protobuf:"varint,3,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 会话ID（接受时返回）
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 响应时间戳
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 被控端设备信息
	TargetInfo    *TargetDeviceInfo `protobuf:"bytes,7,opt,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{8}
}

func (x *ControlResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ControlResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ControlResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlResponse) GetTargetInfo() *TargetDeviceInfo {
	if x != nil {
		return x.TargetInfo
	}
	return nil
}

// TargetDeviceInfo 被控端设备信息
type TargetDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code          uint64                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ScreenWidth   int32                  `protobuf:"varint,5,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int32                  `protobuf:"varint,6,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetDeviceInfo) Reset() {
	*x = TargetDeviceInfo{}
	mi := &file_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDeviceInfo) ProtoMessage() {}

func (x *TargetDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDeviceInfo.ProtoReflect.Descriptor instead.
func (*TargetDeviceInfo) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{9}
}

func (x *TargetDeviceInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TargetDeviceInfo) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TargetDeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *TargetDeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetDeviceInfo) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *TargetDeviceInfo) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

// DisconnectNotify 断开连接通知（控制端 -> 服务器）
type DisconnectNotify struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通知ID
	NotifyId string `protobuf:"bytes,1,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	// 会话ID
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 控制端UUID
	ControllerUuid string `protobuf:"bytes,3,opt,name=controller_uuid,json=controllerUuid,proto3" json:"controller_uuid,omitempty"`
	// 被控端设备码
	TargetDeviceCode uint64 `protobuf:"varint,4,opt,name=target_device_code,json=targetDeviceCode,proto3" json:"target_device_code,omitempty"`
	// 断开原因: 0=主动断开, 1=连接超时, 2=网络错误, 3=被踢出, 4=程序退出
	Reason int32 `protobuf:"varint,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// 原因描述
	ReasonDesc string `protobuf:"bytes,6,opt,name=reason_desc,json=reasonDesc,proto3" json:"reason_desc,omitempty"`
	// 通知时间戳
	Timestamp     int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectNotify) Reset() {
	*x = DisconnectNotify{}
	mi := &file_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectNotify) ProtoMessage() {}

func (x *DisconnectNotify) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectNotify.ProtoReflect.Descriptor instead.
func (*DisconnectNotify) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{10}
}

func (x *DisconnectNotify) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *DisconnectNotify) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectNotify) GetControllerUuid() string {
	if x != nil {
		return x.ControllerUuid
	}
	return ""
}

func (x *DisconnectNotify) GetTargetDeviceCode() uint64 {
	if x != nil {
		return x.TargetDeviceCode
	}
	return 0
}

func (x *DisconnectNotify) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *DisconnectNotify) GetReasonDesc() string {
	if x != nil {
		return x.ReasonDesc
	}
	return ""
}

func (x *DisconnectNotify) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DisconnectResponse 断开连接响应
type DisconnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通知ID
	NotifyId string `protobuf:"bytes,1,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	// 会话ID
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 是否成功处理
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 响应时间戳
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectResponse) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *DisconnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DisconnectResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ScreenStreamRequest 屏幕流请求
type ScreenStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 图像质量 1-100
	Quality int32 `protobuf:"varint,2,opt,name=quality,proto3" json:"quality,omitempty"`
	// 目标FPS
	TargetFps int32 `protobuf:"varint,3,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`
	// 操作: start, stop, pause, resume, update_params
	Action        string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStreamRequest) Reset() {
	*x = ScreenStreamRequest{}
	mi := &file_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStreamRequest) ProtoMessage() {}

func (x *ScreenStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStreamRequest.ProtoReflect.Descriptor instead.
func (*ScreenStreamRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenStreamRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ScreenStreamRequest) GetTargetFps() int32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

func (x *ScreenStreamRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ScreenStreamData 屏幕流数据
type ScreenStreamData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话ID
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 图像数据
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// 格式
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// 宽度
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// 高度
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 序列号
	Sequence      int64 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStreamData) Reset() {
	*x = ScreenStreamData{}
	mi := &file_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStreamData) ProtoMessage() {}

func (x *ScreenStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStreamData.ProtoReflect.Descriptor instead.
func (*ScreenStreamData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{13}
}

func (x *ScreenStreamData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenStreamData) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ScreenStreamData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenStreamData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenStreamData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenStreamData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ScreenStreamData) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_channel_proto protoreflect.FileDescriptor

const file_channel_proto_rawDesc = "" +
	"\n" +
	"\rchannel.proto\x12\x06godesk\"W\n" +
	"\x0eChannelRequest\x12\x1f\n" +
	"\vclient_uuid\x18\x01 \x01(\tR\n" +
	"clientUuid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"S\n" +
	"\fRegisterData\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\"L\n" +
	"\rHeartbeatData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xcc\x01\n" +
	"\x12ControlStartedData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fcontroller_uuid\x18\x02 \x01(\tR\x0econtrollerUuid\x12'\n" +
	"\x0fcontroller_name\x18\x03 \x01(\tR\x0econtrollerName\x12'\n" +
	"\x0frequest_control\x18\x04 \x01(\bR\x0erequestControl\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x88\x01\n" +
	"\x10ControlEndedData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\x05R\x06reason\x12\x1f\n" +
	"\vreason_desc\x18\x03 \x01(\tR\n" +
	"reasonDesc\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x87\x01\n" +
	"\x16ScreenStreamStatusData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"{\n" +
	"\x10StatusReportData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc8\x02\n" +
	"\x0eControlRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fcontroller_uuid\x18\x02 \x01(\tR\x0econtrollerUuid\x12'\n" +
	"\x0fcontroller_code\x18\x03 \x01(\x04R\x0econtrollerCode\x12'\n" +
	"\x0fcontroller_name\x18\x04 \x01(\tR\x0econtrollerName\x12,\n" +
	"\x12target_device_code\x18\x05 \x01(\x04R\x10targetDeviceCode\x12'\n" +
	"\x0ftarget_password\x18\x06 \x01(\tR\x0etargetPassword\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12'\n" +
	"\x0frequest_control\x18\b \x01(\bR\x0erequestControl\"\x83\x02\n" +
	"\x0fControlResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rresponse_code\x18\x03 \x01(\x05R\fresponseCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x129\n" +
	"\vtarget_info\x18\a \x01(\v2\x18.godesk.TargetDeviceInfoR\n" +
	"targetInfo\"\xa6\x01\n" +
	"\x10TargetDeviceInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x04R\x04code\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fscreen_width\x18\x05 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x06 \x01(\x05R\fscreenHeight\"\xfc\x01\n" +
	"\x10DisconnectNotify\x12\x1b\n" +
	"\tnotify_id\x18\x01 \x01(\tR\bnotifyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12'\n" +
	"\x0fcontroller_uuid\x18\x03 \x01(\tR\x0econtrollerUuid\x12,\n" +
	"\x12target_device_code\x18\x04 \x01(\x04R\x10targetDeviceCode\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\x05R\x06reason\x12\x1f\n" +
	"\vreason_desc\x18\x06 \x01(\tR\n" +
	"reasonDesc\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"\xa2\x01\n" +
	"\x12DisconnectResponse\x12\x1b\n" +
	"\tnotify_id\x18\x01 \x01(\tR\bnotifyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x85\x01\n" +
	"\x13ScreenStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\aquality\x18\x02 \x01(\x05R\aquality\x12\x1d\n" +
	"\n" +
	"target_fps\x18\x03 \x01(\x05R\ttargetFps\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"\xd0\x01\n" +
	"\x10ScreenStreamData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequence2\xbf\x02\n" +
	"\x0eChannelService\x12B\n" +
	"\n" +
	"DataStream\x12\x16.godesk.ChannelRequest\x1a\x16.godesk.ChannelRequest\"\x00(\x010\x01\x12G\n" +
	"\x12SendControlRequest\x12\x16.godesk.ControlRequest\x1a\x17.godesk.ControlResponse\"\x00\x12N\n" +
	"\x14SendDisconnectNotify\x12\x18.godesk.DisconnectNotify\x1a\x1a.godesk.DisconnectResponse\"\x00\x12P\n" +
	"\x11StartScreenStream\x12\x1b.godesk.ScreenStreamRequest\x1a\x18.godesk.ScreenStreamData\"\x00(\x010\x01B\vZ\t./;godeskb\x06proto3"

var (
	file_channel_proto_rawDescOnce sync.Once
	file_channel_proto_rawDescData []byte
)

func file_channel_proto_rawDescGZIP() []byte {
	file_channel_proto_rawDescOnce.Do(func() {
		file_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)))
	})
	return file_channel_proto_rawDescData
}

var file_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_channel_proto_goTypes = []any{
	(*ChannelRequest)(nil),         // 0: godesk.ChannelRequest
	(*RegisterData)(nil),           // 1: godesk.RegisterData
	(*HeartbeatData)(nil),          // 2: godesk.HeartbeatData
	(*ControlStartedData)(nil),     // 3: godesk.ControlStartedData
	(*ControlEndedData)(nil),       // 4: godesk.ControlEndedData
	(*ScreenStreamStatusData)(nil), // 5: godesk.ScreenStreamStatusData
	(*StatusReportData)(nil),       // 6: godesk.StatusReportData
	(*ControlRequest)(nil),         // 7: godesk.ControlRequest
	(*ControlResponse)(nil),        // 8: godesk.ControlResponse
	(*TargetDeviceInfo)(nil),       // 9: godesk.TargetDeviceInfo
	(*DisconnectNotify)(nil),       // 10: godesk.DisconnectNotify
	(*DisconnectResponse)(nil),     // 11: godesk.DisconnectResponse
	(*ScreenStreamRequest)(nil),    // 12: godesk.ScreenStreamRequest
	(*ScreenStreamData)(nil),       // 13: godesk.ScreenStreamData
}
var file_channel_proto_depIdxs = []int32{
	9,  // 0: godesk.ControlResponse.target_info:type_name -> godesk.TargetDeviceInfo
	0,  // 1: godesk.ChannelService.DataStream:input_type -> godesk.ChannelRequest
	7,  // 2: godesk.ChannelService.SendControlRequest:input_type -> godesk.ControlRequest
	10, // 3: godesk.ChannelService.SendDisconnectNotify:input_type -> godesk.DisconnectNotify
	12, // 4: godesk.ChannelService.StartScreenStream:input_type -> godesk.ScreenStreamRequest
	0,  // 5: godesk.ChannelService.DataStream:output_type -> godesk.ChannelRequest
	8,  // 6: godesk.ChannelService.SendControlRequest:output_type -> godesk.ControlResponse
	11, // 7: godesk.ChannelService.SendDisconnectNotify:output_type -> godesk.DisconnectResponse
	13, // 8: godesk.ChannelService.StartScreenStream:output_type -> godesk.ScreenStreamData
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_channel_proto_init() }
func file_channel_proto_init() {
	if File_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_proto_goTypes,
		DependencyIndexes: file_channel_proto_depIdxs,
		MessageInfos:      file_channel_proto_msgTypes,
	}.Build()
	File_channel_proto = out.File
	file_channel_proto_goTypes = nil
	file_channel_proto_depIdxs = nil
}
