// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {godesk} from '../models';
import {models} from '../models';

export function AddDevice(arg1:godesk.AddDeviceRequest):Promise<any>;

export function CancelFileTransfer(arg1:string,arg2:string,arg3:string):Promise<any>;

export function CheckFileExists(arg1:string):Promise<any>;

export function CreateSession(arg1:string,arg2:number,arg3:string,arg4:boolean,arg5:string):Promise<any>;

export function DeleteDevice(arg1:godesk.DeleteDeviceRequest):Promise<any>;

export function DeviceInfo():Promise<any>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<any>;

export function EditDevice(arg1:godesk.EditDeviceRequest):Promise<any>;

export function GetAllSessions():Promise<any>;

export function GetConnectionStatus():Promise<any>;

export function GetControlSessionByDeviceCode(arg1:number):Promise<any>;

export function GetControlSessions():Promise<any>;

export function GetDeviceList():Promise<any>;

export function GetFileSessionByDeviceCode(arg1:number):Promise<any>;

export function GetFileTransferStatus(arg1:string):Promise<any>;

export function GetLocalDrives():Promise<any>;

export function GetRemoteFileList(arg1:string,arg2:string):Promise<any>;

export function GetSession(arg1:string):Promise<any>;

export function GetSessionByDeviceCode(arg1:number):Promise<any>;

export function GetSessionImage(arg1:string):Promise<any>;

export function GetSysConfig():Promise<any>;

export function GetUserInfo():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function ListLocalFiles(arg1:string):Promise<any>;

export function Reconnect():Promise<any>;

export function RemoveSession(arg1:string):Promise<any>;

export function RequestRemoteFileList(arg1:string,arg2:string):Promise<any>;

export function SaveSysConfig(arg1:models.SysConfig):Promise<any>;

export function SendControlRequest(arg1:number,arg2:string,arg3:boolean):Promise<any>;

export function SendDisconnectNotify(arg1:string,arg2:number):Promise<any>;

export function SendKeyDown(arg1:string,arg2:string,arg3:Array<string>):Promise<any>;

export function SendKeyUp(arg1:string,arg2:string,arg3:Array<string>):Promise<any>;

export function SendMouseClick(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<any>;

export function SendMouseMove(arg1:string,arg2:number,arg3:number):Promise<any>;

export function SendMouseScroll(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<any>;

export function StopScreenStream(arg1:string):Promise<any>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<any>;

export function UserLogin(arg1:godesk.UserLoginRequest):Promise<any>;

export function UserLogout():Promise<any>;

export function UserRegister(arg1:godesk.UserRegisterRequest):Promise<any>;
