// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeviceInfo() {
  return window['go']['main']['App']['DeviceInfo']();
}

export function EditDevice(arg1) {
  return window['go']['main']['App']['EditDevice'](arg1);
}

export function GetAllSessions() {
  return window['go']['main']['App']['GetAllSessions']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDeviceList() {
  return window['go']['main']['App']['GetDeviceList']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessionByDeviceCode(arg1) {
  return window['go']['main']['App']['GetSessionByDeviceCode'](arg1);
}

export function GetSessionImage(arg1) {
  return window['go']['main']['App']['GetSessionImage'](arg1);
}

export function GetSysConfig() {
  return window['go']['main']['App']['GetSysConfig']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function RemoveSession(arg1) {
  return window['go']['main']['App']['RemoveSession'](arg1);
}

export function SaveSysConfig(arg1) {
  return window['go']['main']['App']['SaveSysConfig'](arg1);
}

export function SendControlRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendControlRequest'](arg1, arg2, arg3);
}

export function SendDisconnectNotify(arg1, arg2) {
  return window['go']['main']['App']['SendDisconnectNotify'](arg1, arg2);
}

export function SendMouseClick(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMouseClick'](arg1, arg2, arg3, arg4, arg5);
}

export function SendMouseMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMouseMove'](arg1, arg2, arg3);
}

export function SendMouseScroll(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMouseScroll'](arg1, arg2, arg3, arg4, arg5);
}

export function StopScreenStream(arg1) {
  return window['go']['main']['App']['StopScreenStream'](arg1);
}

export function UserLogin(arg1) {
  return window['go']['main']['App']['UserLogin'](arg1);
}

export function UserLogout() {
  return window['go']['main']['App']['UserLogout']();
}

export function UserRegister(arg1) {
  return window['go']['main']['App']['UserRegister'](arg1);
}
