// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeviceInfo() {
  return window['go']['main']['App']['DeviceInfo']();
}

export function EditDevice(arg1) {
  return window['go']['main']['App']['EditDevice'](arg1);
}

export function GetDeviceList() {
  return window['go']['main']['App']['GetDeviceList']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UserLogin(arg1) {
  return window['go']['main']['App']['UserLogin'](arg1);
}

export function UserLogout() {
  return window['go']['main']['App']['UserLogout']();
}

export function UserRegister(arg1) {
  return window['go']['main']['App']['UserRegister'](arg1);
}
