// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {godesk} from '../models';

export function AddDevice(arg1:godesk.AddDeviceRequest):Promise<any>;

export function DeleteDevice(arg1:godesk.DeleteDeviceRequest):Promise<any>;

export function DeviceInfo():Promise<any>;

export function EditDevice(arg1:godesk.EditDeviceRequest):Promise<any>;

export function GetDeviceList():Promise<any>;

export function GetUserInfo():Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function UserLogin(arg1:godesk.UserLoginRequest):Promise<any>;

export function UserLogout():Promise<any>;

export function UserRegister(arg1:godesk.UserRegisterRequest):Promise<any>;
